FROM python:3.12.6-slim

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV UV_PROJECT_ENVIRONMENT=/usr/local

COPY --from=ghcr.io/astral-sh/uv:0.10.0 /uv /uvx /usr/local/bin/

RUN mkdir -p /app/src && \
    apt-get update && \
    apt-get install -y git libpq-dev gcc python3-dev libffi-dev musl-dev make libevent-dev
