"""Auto-generated migration

Revision ID: b4678e2231c3
Revises: 6a7c2f2d3b11
Create Date: 2026-05-04 14:30:33.839653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4678e2231c3'
down_revision: Union[str, None] = '6a7c2f2d3b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_model')),
    sa.UniqueConstraint('email', name=op.f('uq__user_model__email'))
    )
    op.create_index(op.f('ix__user_model__email'), 'user_model', ['email'], unique=False)
    op.drop_index('ix__user__email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk__user'),
    sa.UniqueConstraint('email', name='uq__user__email', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix__user__email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix__user_model__email'), table_name='user_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###
